In [1]:
import pandas as pd
import numpy as np

In [2]:
restaurants = pd.read_csv('C:/Users/kimjunseok/Downloads/mealion2/restaurants.csv')

In [3]:
restaurants.head()

,id,name,address,location,regionId
0,1,프로포즈호프,서울특별시 금천구 가산로 34-6,POINT(37.4717112331268 126.899220370682),18.0
1,7,착한짜장,서울특별시 성동구 아차산로7길 17-1,POINT(37.5467182768796 127.054649291142),4.0
2,8,해마로숯불바베큐,서울특별시 성동구 금호산길 62,POINT(37.5536675060871 127.019555900225),4.0
3,10,청암회관,서울특별시 노원구 한글비석로8길 29,POINT(37.6482469290036 127.078464379963),11.0
4,12,배제현의웰빙낙지한마리수제비 강남신사본점,서울특별시 강남구 강남대로152길 19,POINT(37.5175739922091 127.020944625774),23.0

In [12]:
restaurants.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 849868 entries, 0 to 849867
Data columns (total 5 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        849868 non-null  int64
 1   name      849867 non-null  object
 2   address   849868 non-null  object
 3   location  849868 non-null  object
 4   regionId  849867 non-null  float64
dtypes: float64(1), int64(1), object(3)
memory usage: 32.4+ MB

In [4]:
reviews = pd.read_csv('C:/Users/kimjunseok/Downloads/mealion_reviews.csv')

In [6]:
reviews.rename(columns = {'id' : 'userid'}, inplace = True)

In [7]:
reviews.head()

,userid,content,authorId,restaurantId,menus,status,createdAt,updatedAt
0,2,일단 이모들이 너무 친절하고 에너지 넘쳐요!\n반찬은 대체적으로 짠 편이에요ㅜ\n생...,3.0,385515,맛있는생선구이백반,PUBLIC,2020-11-25 12:23:26,2020-11-27 11:36:12
1,3,항상 싸고 맛있게 먹을 수 있다. 다른데가 물가오르면서 다 메뉴가격을 올린반면에 길...,1.0,514251,길낙지볶음,PUBLIC,2020-11-25 12:23:44,2020-11-25 12:28:18
2,4,강원대 체육관 쪽문으로 내려오면 바로 보여요!\n일단 양이 엄~청 많아요!\n게다가...,3.0,341523,"짜장면,짬뽕,미니탕수육",PUBLIC,2020-11-25 12:49:39,2020-11-25 12:53:47
3,6,NaN,NaN,341523,NaN,PRIVATE,2020-11-25 13:18:01,2020-11-25 13:18:01
4,9,투썸은 조각케잌 필수인거 다들 아시죠?!!\n제 최애는 티라미수에요\n먹을때마다 기...,6.0,314108,"티라미수,아메리카노",PUBLIC,2020-11-25 13:23:16,2020-11-25 13:25:07

In [10]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1088 entries, 0 to 1087
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   userid        1088 non-null   int64
 1   content       1034 non-null   object
 2   authorId      1084 non-null   float64
 3   restaurantId  1088 non-null   int64
 4   menus         893 non-null    object
 5   status        1088 non-null   object
 6   createdAt     1088 non-null   object
 7   updatedAt     1088 non-null   object
dtypes: float64(1), int64(2), object(5)
memory usage: 68.1+ KB

In [8]:
review_restaurant = pd.merge(restaurants,reviews, left_on='id',right_on='restaurantId', how='outer' )

In [15]:
review_restaurant = review_restaurant.loc[review_restaurant.content.notna(),: ]

In [26]:
review_restaurant.reset_index(drop=True, inplace=True)

In [27]:
review_restaurant

,id,name,address,location,regionId,userid,content,authorId,restaurantId,menus,status,createdAt,updatedAt
0,2050.0,광히카리마구로,경기도 화성시 동탄문화센터로 71-17,POINT(37.2002534209453 127.072730295024),93.0,301.0,숙성참치 너무 부드럽고 육즙 팡팡터지네요. 동탄최애 참치집입니다. 무한리필보다는 ...,154.0,2050.0,NaN,PUBLIC,2021-01-15 02:52:24,2021-01-15 02:52:24
1,8028.0,오늘통닭3,서울특별시 서대문구 연세로7안길 6,POINT(37.5579663982254 126.936389387062),13.0,1683.0,신촌에서 치맥할 곳 찾다가 들어갔어용 🍗\n\n리뉴얼 하신지 얼마 안된 것 같았어요...,485.0,8028.0,콘치즈통닭L,PUBLIC,2021-05-02 13:28:47,2021-05-02 13:28:47
2,12289.0,수누리감자탕,강원도 춘천시 우석로4번길 5-3,POINT(37.8618418007761 127.746328915694),107.0,1789.0,오랜만에 수누리감자탕에 왔어요\n술은 안먹었지만 뼈해장국을 먹었습니다\n수누리 뼈해...,1.0,12289.0,뼈해장국(8000￦),PUBLIC,2021-06-17 04:44:07,2021-07-05 06:34:24
3,12289.0,수누리감자탕,강원도 춘천시 우석로4번길 5-3,POINT(37.8618418007761 127.746328915694),107.0,1816.0,애막골 근본 맛집 수누리 뼈해장국을 먹었어요!\n더운날에 먹어도 맛있었답니다\n\n...,836.0,12289.0,뻐해장국,PUBLIC,2021-07-03 03:18:19,2021-07-03 03:18:19
4,35516.0,눈내린빙수,강원도 춘천시 백령로23번길 2,POINT(37.8664714987038 127.737379568519),107.0,845.0,강대 정문에 있는 빙수집! \n정말 많은 빙수가 있지만 난 그 중에서 구슬 아이스크...,117.0,35516.0,구슬아이스크림빙수,PUBLIC,2021-02-17 01:52:16,2021-02-17 01:53:50
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1029,851105.0,젤코바(ZELKOVA),강원도 강릉시 종합운동장길 39 1층,POINT(37.77449016017196 128.8935634786165),109.0,1812.0,"🌈 첫 번째. 인테리어\n\n대체로 깔끔하고 감각적인 인테리어였음.\n1층과 지하,...",126.0,851105.0,"아이스바닐라라떼,아이스토피넛라떼",PUBLIC,2021-06-29 09:43:10,2021-06-29 09:44:23
1030,851106.0,HELLO4000,강원도 강릉시 사천면 사천진리 351-17,POINT(37.85125145052771 128.8598379252495),109.0,1813.0,🌈 첫 번째. 인테리어\n\n블랙 앤 화이트 톤으로 전체적으로 모던한 느낌이 듦.\...,126.0,851106.0,"Hello fine,Hello OH!",PUBLIC,2021-06-29 10:54:59,2021-06-29 14:17:09
1031,851107.0,메시56(mesi56),강원도 강릉시 초당순두부길 56,POINT(37.78829292359741 128.914628023726),109.0,1814.0,강릉고등학교 정문 맞은편에 위치한 식당입니다 😎 순두부거리에 있어서 많은 순두부 집...,473.0,851107.0,"오늘의 ‎추천덮밥,우나기동(민물장어) (소)",PUBLIC,2021-06-29 17:01:44,2021-06-29 17:01:44
1032,851108.0,스테딜리,강원도 강릉시 관대길29번길 6-1 1층,POINT(37.73928853482307 128.8782350745145),109.0,1815.0,* 사진을 눌러서 보면 더 자세하게 보실 수 있습니다.\n\n\n• 주소: 강원도 ...,126.0,851108.0,"Ice chocolate,Ice cream latte,Triple berry che...",PUBLIC,2021-06-30 08:48:44,2021-06-30 09:11:04
1033,NaN,NaN,NaN,NaN,NaN,1819.0,"이번에는 강릉에서 색다른 경험을 하고 왔습니다 !\n무려… 와인바인데요,,,!!! ...",845.0,851112.0,NaN,PUBLIC,2021-07-05 10:40:09,2021-07-05 10:40:09

In [17]:
review_restaurant['content']

1999       숙성참치 너무 부드럽고 육즙 팡팡터지네요. 동탄최애 참치집입니다. 무한리필보다는 ...
7922      신촌에서 치맥할 곳 찾다가 들어갔어용 🍗\n\n리뉴얼 하신지 얼마 안된 것 같았어요...
12157     오랜만에 수누리감자탕에 왔어요\n술은 안먹었지만 뼈해장국을 먹었습니다\n수누리 뼈해...
12158     애막골 근본 맛집 수누리 뼈해장국을 먹었어요!\n더운날에 먹어도 맛있었답니다\n\n...
35309     강대 정문에 있는 빙수집! \n정말 많은 빙수가 있지만 난 그 중에서 구슬 아이스크...
                                ...
850146    🌈 첫 번째. 인테리어\n\n대체로 깔끔하고 감각적인 인테리어였음.\n1층과 지하,...
850147    🌈 첫 번째. 인테리어\n\n블랙 앤 화이트 톤으로 전체적으로 모던한 느낌이 듦.\...
850148    강릉고등학교 정문 맞은편에 위치한 식당입니다 😎 순두부거리에 있어서 많은 순두부 집...
850149    * 사진을 눌러서 보면 더 자세하게 보실 수 있습니다.\n\n\n• 주소: 강원도 ...
850150    이번에는 강릉에서 색다른 경험을 하고 왔습니다 !\n무려… 와인바인데요,,,!!! ...
Name: content, Length: 1034, dtype: object

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer


# ngram_range=(1, 2) : 단어를 1개 혹은 2개 연속으로 보겠다
tfidf_vec = TfidfVectorizer(ngram_range=(1,2))
tfidf_matrix = tfidf_vec.fit_transform(review_restaurant['content'])

In [19]:
tfidf_matrix

<1034x68459 sparse matrix of type '<class 'numpy.float64'>'
	with 97544 stored elements in Compressed Sparse Row format>

In [20]:
from sklearn.metrics.pairwise import cosine_similarity

# 4803개의 영화랑 4803개의 영화끼리 유사도를 구하겠다!
# 자신과의 유사도는 1
genres_similarity = cosine_similarity(tfidf_matrix, tfidf_matrix)
print(genres_similarity)

[[1.00000000e+00 0.00000000e+00 1.74129426e-03 ... 5.90019772e-03
  1.25639219e-03 2.67648955e-03]
 [0.00000000e+00 1.00000000e+00 1.41850839e-03 ... 7.81555192e-04
  1.37172938e-03 4.28371442e-03]
 [1.74129426e-03 1.41850839e-03 1.00000000e+00 ... 4.64485828e-03
  2.49484294e-03 6.49315129e-03]
 ...
 [5.90019772e-03 7.81555192e-04 4.64485828e-03 ... 1.00000000e+00
  2.11049864e-02 1.78914182e-02]
 [1.25639219e-03 1.37172938e-03 2.49484294e-03 ... 2.11049864e-02
  1.00000000e+00 9.06551405e-03]
 [2.67648955e-03 4.28371442e-03 6.49315129e-03 ... 1.78914182e-02
  9.06551405e-03 1.00000000e+00]]

In [21]:
# 유사도 값이 높은 영화의 제목
# 유사도 값이 높은 순으로 인덱스 값을 뽑아낸다
similar_index = np.argsort(-genres_similarity)
print(similar_index)
#np.argsort(-genres_similarity)를 수행하면 genres_similarity를 유사도가 높은 순서대로 정렬한 인덱스 numpy 배열을 리턴한다. 
#즉, 각 영화에 해당하는 행마다 자신과 유사한 영화를 순서대로 가지고 있는 배열이 생성되는 것이다.

[[   0  550  945 ...  503  480  516]
 [   1 1008  857 ...  577  565    0]
 [   2    3  333 ...  144  851  127]
 ...
 [1031 1024  437 ...   67  366  722]
 [1032 1029  990 ...  112  920  615]
 [1033  604  755 ...  254  569  542]]

In [22]:
review_restaurant.name

1999           광히카리마구로
7922             오늘통닭3
12157           수누리감자탕
12158           수누리감자탕
35309            눈내린빙수
              ...
850146    젤코바(ZELKOVA)
850147       HELLO4000
850148    메시56(mesi56)
850149            스테딜리
850150             NaN
Name: name, Length: 1034, dtype: object

In [34]:
input_restaurant = input()

restaurant_index = review_restaurant[review_restaurant['name']==input_restaurant].index.values
similar_restaurants = similar_index[restaurant_index, :10]

# 인덱스로 사용하기 용이하도록 1차원으로 변경
similar_restaurant_index = similar_restaurants.reshape(-1)

display(review_restaurant.iloc[similar_restaurant_index])

HELLO4000

,id,name,address,location,regionId,userid,content,authorId,restaurantId,menus,status,createdAt,updatedAt
1030,851106.0,HELLO4000,강원도 강릉시 사천면 사천진리 351-17,POINT(37.85125145052771 128.8598379252495),109.0,1813.0,🌈 첫 번째. 인테리어\n\n블랙 앤 화이트 톤으로 전체적으로 모던한 느낌이 듦.\...,126.0,851106.0,"Hello fine,Hello OH!",PUBLIC,2021-06-29 10:54:59,2021-06-29 14:17:09
559,850523.0,큰지붕닭갈비,강원 춘천시 신북읍 신샘밭로 652,POINT(37.92965736027466 127.7819817685266),107.0,1050.0,oh,3.0,850523.0,"닭갈비,볶음밥,치즈",PUBLIC,2021-02-28 13:49:48,2021-07-02 13:08:50
990,851056.0,ALLOF(올오브),강원도 강릉시 정원로 73-1,POINT(37.76249945005116 128.8735158930699),109.0,1653.0,🌈 첫 번째. 인테리어\n\n우선 딱 한 마디로 말 하자면 심플했음.\n대체로 실버...,126.0,851056.0,"아이스아메리카노,자몽에이드",PUBLIC,2021-04-25 17:10:59,2021-04-26 03:55:09
1029,851105.0,젤코바(ZELKOVA),강원도 강릉시 종합운동장길 39 1층,POINT(37.77449016017196 128.8935634786165),109.0,1812.0,"🌈 첫 번째. 인테리어\n\n대체로 깔끔하고 감각적인 인테리어였음.\n1층과 지하,...",126.0,851105.0,"아이스바닐라라떼,아이스토피넛라떼",PUBLIC,2021-06-29 09:43:10,2021-06-29 09:44:23
1032,851108.0,스테딜리,강원도 강릉시 관대길29번길 6-1 1층,POINT(37.73928853482307 128.8782350745145),109.0,1815.0,* 사진을 눌러서 보면 더 자세하게 보실 수 있습니다.\n\n\n• 주소: 강원도 ...,126.0,851108.0,"Ice chocolate,Ice cream latte,Triple berry che...",PUBLIC,2021-06-30 08:48:44,2021-06-30 09:11:04
245,502272.0,쎄라비,강원도 강릉시 하슬라로206번길 19-12,POINT(37.7686393009215 128.878255479853),109.0,1199.0,🌈 첫 번째. 인테리어\n\n맨날 사진으로 담는다는게 자꾸 인테리어 찍는 걸 깜빡하...,126.0,502272.0,"팥라떼,파블로바",PUBLIC,2021-03-17 11:59:43,2021-03-21 16:56:31
858,850910.0,놀커피,강원도 강릉시 초당원길 38-10 1층,POINT(37.78569453792868 128.9162575058789),109.0,1117.0,아직은 가오픈 운영 중인 신상 카페 놀커피에요!\n요본달인 3월 중으로 정식 오픈 ...,126.0,850910.0,"딸기라떼,연유라떼,패션후르츠에이드,바스크치즈케이크",PUBLIC,2021-03-07 15:00:18,2021-03-17 12:02:15
991,851059.0,온센(강릉점),강원도 강릉시 창해로 13,POINT(37.77340625172933 128.945217555476),109.0,1654.0,🌈 첫 번째. 인테리어\n\n대체로 화이트/우드 톤의 아늑한 느낌임.\n주방쪽과 창...,126.0,851059.0,"온센텐동,보리멸텐동,유자바질토마토",PUBLIC,2021-04-25 17:46:12,2021-04-25 17:46:12
730,850764.0,저문강에 삽을씻고,강원도 횡성군 화성로 104,POINT(37.49937550846831 127.9922266393972),115.0,661.0,찹스테이크 부드럽진 않지만 맛있음. 밥은 조금 질음. \n차돌박이 로제파스타는 꾸덕...,469.0,850764.0,"찹스테이크,차돌박이로제파스타",PUBLIC,2021-02-06 13:36:12,2021-02-06 13:36:12
243,502255.0,피그놀리아커피,강원도 강릉시 난설헌로 195,POINT(37.7909941342751 128.911400786498),109.0,1796.0,캠핑을 가기에는 시간이 부족한데 특별한 추억을 만들어야해서 카페 야외에 있는 꾸며놓...,65.0,502255.0,"아메리카노,토피넛 라떼,딸기라떼,레몬베리에이드",PUBLIC,2021-06-21 07:39:20,2021-06-21 07:39:20

<정보가 부족한 신규 유저를 위한 추천 알고리즘>

#counterVectorizer 보다 그럴 듯한 식당을 추천해준다
#단점: 데이터 85만개가 아니라, 1000개로 추천을 해준다. 
전국단위 추천을 하지 못한다.
어떻게 하면 TF-IDF 추천 알고리즘을 사용할 수 있을까???
우선 추천 순위를 TF-IDF, 리뷰가 부족한 곳에는 그 다음 순위로 Countervectorizer도 식당을 추천해준다. 그럼 데이터가 1000개에서 2000개로 늘어난다.... 
1순위) TF-IDF : 리뷰를 분석해 유사한 추천 맛집을 알려준다- 더 사용자 취향에 어울리는 세심하게 맛집을 추천해줄 수 있다.
2순위) CounterVectorizer: 같은 카테고리(한식, 일식, 양식...) 순으로, 평점 수, 평점 평균 순으로 추천해준다. - 덜 세심하지만, 그럴 듯하게 사용자에게 맞는 맛집을 추천해준다.
3순위)
-권장: 리뷰와 평점 데이터를 많이 확보하다. 
많이 확보하면 
1만개 이상으로 (85만개 그정도로 필요 없으니깐, 인기있는집, 알게 모르게 많이가는 집, 새로 생긴 음식점 위주로 1~5만개만 뽑아도 된다) -> 리뷰와 평점을 어떻게 얻지? 
1. 공공데이터나 사적 데이터 얻기
2. 크롤링으로 네이버, 구글, 카카오 지도 등에서 얻다.


컨텐츠 기반 추천 알고리즘도 사전 지역 선택 추천 알고리즘으로 만들 수 있을까?
사전 지역 선택 추천 알고리즘이란: 사용자의 id를 미리 가지고, 지역을 미리 선택해서